version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestExtPrjProject
  gitServerName: test1
  gitUrl: https://github.com/PoojaAnandGit
  gitUsername: PoojaAnandGit
  gitBranch: main
services:
- serviceName: project.testextprj.integrations:testedge1
  packages:
  - name: TestExtPrjProject
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2023
